"Rules for generating .props files to sync IDE with Bazel-generated sources"

load("@bazel_lib//lib:write_source_files.bzl", "write_source_file")
load("@xml.bzl", "xml")

def _generated_props_content_impl(ctx):
    """Generate the content of a .props file with Compile includes."""
    props_file = ctx.outputs.out

    # Collect all source file paths
    source_paths = []
    for src in ctx.files.generated_srcs:
        source_paths.append(src.short_path)

    # Build comment text
    update_target = ctx.attr.update_target if ctx.attr.update_target else "//:" + ctx.label.name.replace("_content", "")
    comment_text = " DO NOT EDIT - Generated by Bazel. Run 'bazel run {}' to update. ".format(update_target)

    # Build Compile elements for each source file
    compile_elements = []
    for path in source_paths:
        link_path = _compute_link_path(path)

        # Create <Compile Include="..."><Link>...</Link></Compile>
        compile_elem = xml.element("Compile", {
            "Include": "$(MSBuildThisFileDirectory){}".format(path),
        }, [
            xml.element("Link", children = [xml.text(link_path)]),
        ])
        compile_elements.append(compile_elem)

    # Build the XML document structure
    doc = xml.document(
        xml_declaration = 'version="1.0" encoding="utf-8"',
        children = [
            xml.comment(comment_text),
            xml.element("Project", children = [
                xml.element("ItemGroup", {"Label": "Bazel Generated Sources"}, compile_elements),
            ]),
        ],
    )

    # Serialize to string
    content = xml.to_string(doc, pretty = True)

    ctx.actions.write(
        output = props_file,
        content = content + "\n",
    )

    return [DefaultInfo(files = depset([props_file]))]

def _compute_link_path(bazel_path):
    """Compute the Link path for IDE display.

    Args:
        bazel_path: The bazel short_path to the generated file.

    Returns:
        A clean path for the IDE's Solution Explorer display.
    """

    # Remove bazel-out/.../bin/ prefix if present
    if "bazel-out/" in bazel_path:
        parts = bazel_path.split("/bin/", 1)
        if len(parts) > 1:
            bazel_path = parts[1]

    # Put generated files under a "Generated" folder in IDE
    return "Generated/" + bazel_path.split("/")[-1]

_generated_props_content = rule(
    implementation = _generated_props_content_impl,
    attrs = {
        "generated_srcs": attr.label_list(
            allow_files = True,
            doc = "List of generated source file targets to include in the .props file.",
        ),
        "update_target": attr.string(
            doc = "Label of the write_source_file target for the update message.",
        ),
    },
    outputs = {
        "out": "%{name}.props",
    },
    doc = "Generate the content of a .props file with Compile includes for generated sources.",
)

def dotnet_generated_props(
        name,
        generated_srcs,
        out = None,
        suggested_update_target = None,
        **kwargs):
    """Generate a .props file to sync IDE with Bazel-generated sources.

    This creates a .props file containing `<Compile Include="...">` elements for
    Bazel-generated source files. The .props file can be imported into a .csproj
    to enable IDE features (IntelliSense, Go to Definition) for generated code.

    Usage in BUILD.bazel:
    ```
    load("@rules_dotnet//dotnet:defs.bzl", "dotnet_generated_props")

    proto_csharp_library(
        name = "my_protos",
        protos = ["//proto:services"],
    )

    dotnet_generated_props(
        name = "sync_ide",
        generated_srcs = [":my_protos"],
        out = "MyProject.Generated.props",
    )
    ```

    Usage in .csproj:
    ```xml
    <Project Sdk="Microsoft.NET.Sdk">
      <Import Project="MyProject.Generated.props"
              Condition="Exists('MyProject.Generated.props')" />
    </Project>
    ```

    To update the .props file:
    ```bash
    bazel run //:sync_ide
    ```

    Args:
        name: Target name. Use this with `bazel run` to update the .props file.
        generated_srcs: List of labels to Bazel-generated source files.
        out: Output filename (default: "{name}.props" in the current package).
        suggested_update_target: Override the update target shown in the generated comment.
        **kwargs: Additional arguments passed to write_source_file.

    Returns:
        Creates two targets:
        - {name}_content: The generated .props content
        - {name}: The write_source_file target to sync the checked-in file
    """
    if not generated_srcs:
        fail("generated_srcs must not be empty")

    content_name = name + "_content"
    out_file = out or (name + ".props")
    update_target = suggested_update_target or "//{}:{}".format(native.package_name(), name)

    _generated_props_content(
        name = content_name,
        generated_srcs = generated_srcs,
        update_target = update_target,
    )

    write_source_file(
        name = name,
        in_file = ":" + content_name,
        out_file = out_file,
        **kwargs
    )

def dotnet_generated_props_test(
        name,
        generated_srcs,
        out,
        **kwargs):
    """Test that a .props file is up-to-date with generated sources.

    This is the test-only version that fails if the .props file needs updating.
    Use in CI to ensure generated files are committed.

    Args:
        name: Target name.
        generated_srcs: List of labels to Bazel-generated source files.
        out: The .props file to check.
        **kwargs: Additional arguments passed to write_source_file.
    """
    content_name = name + "_content"

    _generated_props_content(
        name = content_name,
        generated_srcs = generated_srcs,
        update_target = "//{}:{}".format(native.package_name(), name.replace("_test", "")),
    )

    write_source_file(
        name = name,
        in_file = ":" + content_name,
        out_file = out,
        diff_test = True,
        **kwargs
    )
